//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

// Generates scoped chroma CSS for light and dark themes. Each rule is prefixed
// with [data-theme="light|dark"] so the browser can switch at runtime.
// chroma emits one rule per line: `/* Name */ .sel { decls }`.
var leadingComment = regexp.MustCompile(`^\s*(/\*.*?\*/\s*)?`)

func main() {
	gen("github", "light", "internal/assets/static/chroma-light.css")
	gen("github-dark", "dark", "internal/assets/static/chroma-dark.css")
}

func gen(style, theme, out string) {
	s := styles.Get(style)
	if s == nil {
		panic("style not found: " + style)
	}
	f := chromahtml.New(chromahtml.WithClasses(true))
	var buf strings.Builder
	if err := f.WriteCSS(&buf, s); err != nil {
		panic(err)
	}
	prefix := fmt.Sprintf(`[data-theme="%s"] `, theme)
	fh, err := os.Create(out)
	if err != nil {
		panic(err)
	}
	defer fh.Close()
	w := bufio.NewWriter(fh)
	fmt.Fprintf(w, "/* generated by tools/genchroma from chroma style %q */\n", style)
	for _, line := range strings.Split(buf.String(), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		body := leadingComment.ReplaceAllString(line, "")
		brace := strings.Index(body, "{")
		if brace < 0 {
			continue
		}
		sel := strings.TrimSpace(body[:brace])
		rest := body[brace:]
		parts := strings.Split(sel, ",")
		for i := range parts {
			parts[i] = prefix + strings.TrimSpace(parts[i])
		}
		fmt.Fprintln(w, strings.Join(parts, ", ")+" "+rest)
	}
	w.Flush()
	fmt.Println("wrote", out)
}
